export const categories = [
  {
    level: 0,
    isActive: true, isDeleted: false,
    description: "Gadgets",
    name: "Samsung Galaxy-M1",
    banner: "/assets/images/products/samsung.png",
    service: {
      isActive: true, isDeleted: false,
      description: "Gadgets",
      name: "Samsung Galaxy-M1",
    },
  },
  {
    level: 1,
    isActive: true, isDeleted: false,
    name: "Tomatto",
    description: "Grocery",
    banner: "/assets/images/products/tomato.png",
    service: {
      isActive: true, isDeleted: false,
      description: "Gadgets",
      name: "Samsung Galaxy-M1",
    },
  },
  {
    level: 0,
    isActive: false, isDeleted: true,
    description: "Beauty",
    name: "Boston Round Cream Pack",
    banner: "/assets/images/products/beauty-cream.png",
    service: {
      isActive: true, isDeleted: false,
      description: "Gadgets",
      name: "Samsung Galaxy-M1",
    },
  },
  {
    level: 1,
    isActive: true, isDeleted: false,
    description: "Fashion",
    name: "Woman Party Dress",
    banner: "/assets/images/products/red-dress.png",
    service: {
      isActive: true, isDeleted: false,
      description: "Gadgets",
      name: "Samsung Galaxy-M1",
    },
  },
  {
    level: 0,
    isActive: true, isDeleted: false,
    name: "White Tops",
    description: "Fashion",
    banner: "/assets/images/products/white-tops.png",
    service: {
      isActive: true, isDeleted: false,
      description: "Gadgets",
      name: "Samsung Galaxy-M1",
    },
  },
  {
    level: 1,
    isActive: false, isDeleted: true,
    description: "Fashion",
    name: "Casual Shirt for Man",
    banner: "/assets/images/products/formal-shirt.png",
    service: {
      isActive: true, isDeleted: false,
      description: "Gadgets",
      name: "Samsung Galaxy-M1",
    },
  },
  {
    level: 0,
    isActive: true, isDeleted: false,
    description: "Fashion",
    name: "Blue Premium T-shirt",
    banner: "/assets/images/products/blu-tshirt.png",
    service: {
      isActive: true, isDeleted: false,
      description: "Gadgets",
      name: "Samsung Galaxy-M1",
    },
  },
  {
    level: 1,
    isActive: false, isDeleted: true,
    description: "Fashion",
    name: "Man Trowzer Pant",
    banner: "/assets/images/products/pnat.png",
    service: {
      isActive: true, isDeleted: false,
      description: "Gadgets",
      name: "Samsung Galaxy-M1",
    },
  },
];
